Python-Screening-Task-1-UI-UX-Enhancement/workshop_booking-master-new/cms/urls.py
from django.conf.urls import url

from cms import views

app_name = "cms"

urlpatterns = [
    url('^$', views.home, name='home'),
    url('^(?P<permalink>.+)$', views.home, name='home')
]

Python-Screening-Task-1-UI-UX-Enhancement/workshop_booking-master-new/statistics_app/urls.py
from django.urls import path
from statistics_app import views

app_name = "statistics_app"

urlpatterns = [
    path('public', views.workshop_public_stats, name="public"),
    path('team', views.team_stats, name="team"),
    path('team/<int:team_id>', views.team_stats, name="team"),
]

Python-Screening-Task-1-UI-UX-Enhancement/workshop_booking-master-new/workshop_app/urls.py
from django.conf.urls import url
from workshop_app import views

app_name = "workshop_app"

urlpatterns = [
    url(r'^$', views.index, name='index'),
    url(r'^register/$', views.user_register, name="register"),
    url(r'^activate_user/(?P<key>.+)$', views.activate_user),
    url(r'^activate_user/$', views.activate_user),
    url(r'^login/$', views.user_login, name="login"),
    url(r'^logout/$', views.user_logout, name="logout"),
    url(r'^status$', views.workshop_status_coordinator,
        name='workshop_status_coordinator'),
    url(r'^dashboard$', views.workshop_status_instructor,
        name='workshop_status_instructor'),
    url(r'^accept_workshop/(?P<workshop_id>\d+)', views.accept_workshop,
        name='accept_workshop'),
    url(r'^change_workshop_date/(?P<workshop_id>\d+)$',
        views.change_workshop_date, name='change_workshop_date'),
    url(r'^details/(?P<workshop_id>\d+)$', views.workshop_details,
        name='workshop_details'),
    url(r'^type_details/(?P<workshop_type_id>\d+)$',
        views.workshop_type_details, name='workshop_type_details'),
    url(r'^type_tnc/(?P<workshop_type_id>\d+)$',
        views.workshop_type_tnc, name='workshop_type_tnc'),
    url(r'^propose/$', views.propose_workshop,
        name='propose_workshop'),
    url(r'^add_workshop_type$', views.add_workshop_type,
        name='add_workshop_type'),
    url(r'^delete_attachment_file/(?P<file_id>\d+)$',
        views.delete_attachment_file, name='delete_attachment_file'),
    url(r'^types/$', views.workshop_type_list,
        name='workshop_type_list'),
    url(r'^view_profile/$', views.view_own_profile,
        name='view_own_profile'),
    url(r'^view_profile/(?P<user_id>\d+)$', views.view_profile,
        name='view_profile'),
]

Python-Screening-Task-1-UI-UX-Enhancement/workshop_booking-master-new/workshop_portal/urls.py
from django.conf.urls import url, include
from django.conf.urls.static import static
from django.contrib import admin
from workshop_portal import views
from django.conf import settings


urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^$', views.index),
    url(r'^workshop/', include('workshop_app.urls')),
    url(r'^reset/', include('django.contrib.auth.urls')),
    url(r'^page/', include('cms.urls')),
    url(r'^statistics/', include('statistics_app.urls')),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

Python-Screening-Task-1-UI-UX-Enhancement/workshop_booking-master-new/workshop_app/models.py
import os
import uuid
import pandas as pd

from django.contrib.auth.models import User
from django.core.validators import RegexValidator
from django.db import models
from django.utils import timezone
from django.core.validators import MinValueValidator

position_choices = (
    ("coordinator", "Coordinator"),
    ("instructor", "Instructor")
)

department_choices = (
    ("computer engineering", "Computer Science"),
    ("information technology", "Information Technology"),
    ("civil engineering", "Civil Engineering"),
    ("electrical engineering", "Electrical Engineering"),
    ("mechanical engineering", "Mechanical Engineering"),
    ("chemical engineering", "Chemical Engineering"),
    ("aerospace engineering", "Aerospace Engineering"),
    ("biosciences and bioengineering", "Biosciences and  BioEngineering"),
    ("electronics", "Electronics"),
    ("energy science and engineering", "Energy Science and Engineering"),
)

title = (
    ("Professor", "Prof."),
    ("Doctor", "Dr."),
    ("Shriman", "Shri"),
    ("Shrimati", "Smt"),
    ("Kumari", "Ku"),
    ("Mr", "Mr."),
    ("Mrs", "Mrs."),
    ("Miss", "Ms."),
)

source = (
    ("FOSSEE website", "FOSSEE website"),
    ("Google", "Google"),
    ("Social Media", "Social Media"),
    ("From other College", "From other College"),
)

states = (
    ("", "---------"),
    ("IN-AP", "Andhra Pradesh"),
    ("IN-AR", "Arunachal Pradesh"),
    ("IN-AS", "Assam"),
    ("IN-BR", "Bihar"),
    ("IN-CT", "Chhattisgarh"),
    ("IN-GA", "Goa"),
    ("IN-GJ", "Gujarat"),
    ("IN-HR", "Haryana"),
    ("IN-HP", "Himachal Pradesh"),
    ("IN-JK", "Jammu and Kashmir"),
    ("IN-JH", "Jharkhand"),
    ("IN-KA", "Karnataka"),
    ("IN-KL", "Kerala"),
    ("IN-MP", "Madhya Pradesh"),
    ("IN-MH", "Maharashtra"),
    ("IN-MN", "Manipur"),
    ("IN-ML", "Meghalaya"),
    ("IN-MZ", "Mizoram"),
    ("IN-NL", "Nagaland"),
    ("IN-OR", "Odisha"),
    ("IN-PB", "Punjab"),
    ("IN-RJ", "Rajasthan"),
    ("IN-SK", "Sikkim"),
    ("IN-TN", "Tamil Nadu"),
    ("IN-TG", "Telangana"),
    ("IN-TR", "Tripura"),
    ("IN-UT", "Uttarakhand"),
    ("IN-UP", "Uttar Pradesh"),
    ("IN-WB", "West Bengal"),
    ("IN-AN", "Andaman and Nicobar Islands"),
    ("IN-CH", "Chandigarh"),
    ("IN-DN", "Dadra and Nagar Haveli"),
    ("IN-DD", "Daman and Diu"),
    ("IN-DL", "Delhi"),
    ("IN-LD", "Lakshadweep"),
    ("IN-PY", "Puducherry")
)


def has_profile(user):
    """ check if user has profile """
    return hasattr(user, 'profile')


def attachments(instance, filename):
    return os.sep.join((instance.workshop_type.name.replace(" ", '_'), filename))


class Profile(models.Model):
    """Profile for users(instructors and coordinators)"""

    user = models.OneToOneField(User, on_delete=models.CASCADE)
    title = models.CharField(max_length=32, blank=True, choices=title)
    institute = models.CharField(max_length=150)
    department = models.CharField(max_length=150, choices=department_choices)
    phone_number = models.CharField(
        max_length=10,
        validators=[RegexValidator(
            regex=r'^.{10}$', message=(
                "Phone number must be entered \
                in the format: '9999999999'.\
                Up to 10 digits allowed.")
        )], null=False)
    position = models.CharField(
            max_length=32, choices=position_choices,
            default='coordinator',
            help_text='Select Coordinator if you want to organise a workshop\
         in your college/school. <br> Select Instructor if you want to conduct\
                 a workshop.')
    how_did_you_hear_about_us = models.CharField(
        max_length=255, blank=True, choices=source
    )
    location = models.CharField(
        max_length=255, blank=True, help_text="Place/City"
    )
    state = models.CharField(max_length=255, choices=states, default="IN-MH")
    is_email_verified = models.BooleanField(default=False)
    activation_key = models.CharField(max_length=255, blank=True, null=True)
    key_expiry_time = models.DateTimeField(blank=True, null=True)

    def __str__(self):
        return f"Profile for {self.user.get_full_name()}"


class WorkshopType(models.Model):
    """"Admin creates types of workshops which can be used by the instructor
        to create workshops.
    """

    name = models.CharField(max_length=120)
    description = models.TextField()
    duration = models.PositiveIntegerField(
        help_text='Please enter duration in days',
        validators=[MinValueValidator(1)]
    )
    terms_and_conditions = models.TextField()

    def __str__(self):
        return f"{self.name} for {self.duration} day(s)"


class AttachmentFile(models.Model):
    attachments = models.FileField(
        upload_to=attachments, blank=False,
        help_text='Please upload workshop documents one by one, \
                    ie.workshop schedule, instructions etc. \
                    Please Note: Name of Schedule file should be similar to \
                    WorkshopType Name')
    workshop_type = models.ForeignKey(WorkshopType, on_delete=models.CASCADE)


class WorkshopManager(models.Manager):

    def get_workshops_by_state(self, workshops):
        w = workshops.values_list("coordinator__profile__state", flat=True)
        states_map = dict(states)
        df = pd.DataFrame(list(w))
        data_states, data_counts = [], []
        if not df.empty:
            grouped_data = df.value_counts().to_dict()
            for state, count in grouped_data.items():
                state_name = state[0]
                data_states.append(states_map[state_name])
                data_counts.append(count)
        return data_states, data_counts

    def get_workshops_by_type(self, workshops):
        w = workshops.values_list("workshop_type__name", flat=True)
        df = pd.DataFrame(list(w))
        data_wstypes, data_counts = [], []
        if not df.empty:
            grouped_data = df.value_counts().to_dict()
            for ws, count in grouped_data.items():
                ws_name = ws[0]
                data_wstypes.append(ws_name)
                data_counts.append(count)
        return data_wstypes, data_counts


class Workshop(models.Model):
    """
        Contains details of workshops
    """
    uid = models.UUIDField(default=uuid.uuid4, unique=True, editable=False)
    coordinator = models.ForeignKey(User, on_delete=models.CASCADE)
    instructor = models.ForeignKey(
        User, null=True, related_name="%(app_label)s_%(class)s_related",
        on_delete=models.CASCADE
    )
    workshop_type = models.ForeignKey(
        WorkshopType, on_delete=models.CASCADE,
        help_text='Select the type of workshop.'
    )
    date = models.DateField()
    STATUS_CHOICES = [(0, 'Pending'),
                      (1, 'Accepted'),
                      (2, 'Deleted')]

    status = models.IntegerField(choices=STATUS_CHOICES, default=0)
    tnc_accepted = models.BooleanField(
        help_text="I accept the terms and conditions"
    )

    objects = WorkshopManager()

    def __str__(self):
        return f"{self.workshop_type} on {self.date} by {self.coordinator}"

    def get_status(self):
        choice = dict(self.STATUS_CHOICES)
        return choice.get(self.status)




class Testimonial(models.Model):
    """
    Contains Testimonals of Workshops
    """

    name = models.CharField(max_length=150)
    institute = models.CharField(max_length=255)
    department = models.CharField(max_length=150)
    message = models.TextField()

    def __str__(self):
        return f"Testimonial by {self.name}"


class Comment(models.Model):
    """
    Contains comments posted by users on workshop instances
    """

    author = models.ForeignKey(User, on_delete=models.CASCADE)
    comment = models.TextField()
    public = models.BooleanField(default=True)
    created_date = models.DateTimeField(default=timezone.now)
    workshop = models.ForeignKey(Workshop, on_delete=models.CASCADE)

    def __str__(self):
        return f"Comment by {self.author.get_full_name()}"


class Banner(models.Model):
    """
    Add HTML for banner display on homepage
    """
    title = models.CharField(max_length=500)
    html = models.TextField()
    active = models.BooleanField()

    def __str__(self):
        return self.title

Python-Screening-Task-1-UI-UX-Enhancement/workshop_booking-master-new/workshop_app/templates/workshop_app/activation.html
{% extends 'workshop_app/base.html' %}

{% block title %}
    Awaiting activation
{% endblock %}

{% block header %}
    <nav class="navbar navbar-default navbar-dark bg-dark">
        <div class="container-fluid">
            <div class="navbar-header">
                <a class="navbar-brand text-white" href="/">
                    FOSSEE Workshops
                </a>
            </div>
            <ul class="nav navbar-nav navbar-right">
                {% if request.user.profile.is_email_verified %}
                    <li><a href="{% url 'workshop_app:view_profile' %}"><span class="glyphicon glyphicon-user"></span>
                        Profile</a></li>

                    <li><a href="{% url 'workshop_app:logout' %}"><span class="glyphicon glyphicon-log-out"></span> Logout</a>
                    </li>
                {% endif %}
            </ul>
        </div>
    </nav>
{% endblock %}

{% block extra %}

{% endblock %}

{% block content %}
    {% if status == '2' %}
        <div class="container">
            <div class="jumbotron">
                <p> Your email is already verified, Click
                    <a href="{% url 'workshop_app:index' %}">here</a>
                </p>
            </div>
        </div>
    {% elif status == '1' %}
        <script type="text/javascript">
            window.setTimeout(function () {
                location.href = "{% url 'workshop_app:register' %}"
            }, 3000);
        </script>
        <div class="container">
            <div class="jumbotron">
                <p> Your activation has expired please register again</p>
            </div>
        </div>
    {% elif status == '0' %}
        <div class="container">
            <div class="jumbotron">
                <p> Your account has been activated. Click
                    <a href="{% url 'workshop_app:index' %}">here</a>
                </p>
            </div>
        </div>
    {% else %}
        <script type="text/javascript">
            window.setTimeout(function () {
                location.href = "{% url 'workshop_app:logout' %}"
            }, 5000);
        </script>

        <div class="container">
            <div class="jumbotron">
                <h1>Activation Awaiting</h1>
                <p>The Activation Link has been sent to your email. The link expires in <strong>24hours</strong> from
                    the date of registration. You will be logged out automatically
                </p>
            </div>
        </div>
    {% endif %}
{% endblock %}

Python-Screening-Task-1-UI-UX-Enhancement/workshop_booking-master-new/workshop_app/templates/workshop_app/add_workshop_type.html
{% extends 'workshop_app/base.html' %}

{% block title %}
    Add new Workshop type
{% endblock %}

{% block content %}
    <div class="container">
        <h2 class="text-center m-2">New Workshop Type</h2>
        <br>
        <form method="post">
            <div class="row my-3">
                <div class="col-3 font-weight-bold">Workshop Name :</div>
                <div class="col text-left">
                    <div class="row"><div class="col">{{ form.name }}</div></div>
                    <div class="row m-1 text-danger"><div class="col">{{ form.name.errors }}</div></div>
                </div>

            </div>
            <div class="row my-3">
                <div class="col-3 font-weight-bold">Duration :</div>
                <div class="col text-left">
                    <div class="row"><div class="col">{{ form.duration }}</div></div>
                    <div class="row m-1 text-muted"><div class="col">{{ form.duration.help_text }}</div></div>
                    <div class="row m-1 text-danger"><div class="col">{{ form.duration.errors }}</div></div>
                </div>
            </div>
            <div class="row my-3">
                <div class="col-3 font-weight-bold">Description :</div>
                <div class="col text-left">
                    <div class="row"><div class="col">{{ form.description }}</div></div>
                    <div class="row m-1 text-danger"><div class="col">{{ form.description.errors }}</div></div>
                </div>
            </div>
            <div class="row my-3">
                <div class="col-3 font-weight-bold">Terms and Conditions :</div>
                <div class="col text-left">
                    <div class="row"><div class="col">{{ form.terms_and_conditions }}</div></div>
                    <div class="row m-1 text-danger"><div class="col">{{ form.terms_and_conditions.errors }}</div></div>
                </div>
            </div>

            <div class="row my-3">
                <div class="col-12">
                    <button type="submit" class="btn btn-md btn-primary float-right m-3">Create</button>
                </div>
            </div>
        </form>
    </div>
{% endblock %}

Python-Screening-Task-1-UI-UX-Enhancement/workshop_booking-master-new/workshop_app/templates/workshop_app/base.html
<!DOCTYPE html>
<html lang="en">
{% load static %}
{% load custom_filters %}
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="theme-color" content="#0d6efd">
    <title>
        {% block title %}
            HomePage
        {% endblock %}
    </title>

    

    {% block extra-dependencies %}
    {% endblock %}

    <link rel="stylesheet" href="{% static 'workshop_app/css/bootstrap.min.css' %}">
    <link rel="stylesheet" href="{% static 'workshop_app/css/toastr.min.css' %}">
    <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
    <link rel="stylesheet" href="{% static 'workshop_app/css/base.css' %}" type="text/css"/>
    <link rel="stylesheet" href="{% static 'workshop_app/css/font-awesome.css' %}" type="text/css"/>
    
    {% block extra-custom-scripts %}
    {% endblock %}

</head>

<body>
<a class="skip-link" href="#main">Skip to main content</a>
{% block header %}
    <nav class="navbar navbar-dark navbar-expand-lg bg-dark fixed-top">
        <div class="container">
        <a class="navbar-brand text-white" href="{% url 'workshop_app:index' %}">FOSSEE Workshops</a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent"
                aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <ul class="navbar-nav">
                <li class="nav-item">
                    <a class="nav-link text-white" href="{% url 'workshop_app:index' %}">
                        Home
                    </a>
                </li>
                <li class="nav-item">
                    <a class="nav-link text-white" href="{% url 'statistics_app:public' %}">
                        Workshop Statistics
                    </a>
                </li>
            </ul>
            {% if user.is_authenticated %}
            <ul class="navbar-nav mr-auto">
                {% if request.user|has_group:"instructor" %}
                <li class="nav-item">
                    <a class="nav-link text-white" href="{% url 'statistics_app:team' %}">
                        Team Statistics
                    </a>
                </li>
                {% endif %}
                <li class="nav-item">
                    <a class="nav-link text-white" href="{% url 'workshop_app:workshop_status_instructor' %}">
                        Workshop Status
                    </a>
                </li>
                {% if not request.user|has_group:"instructor" %}
                    <li class="nav-item">
                        <a class="nav-link text-white" href="{% url 'workshop_app:propose_workshop' %}">
                            Propose Workshop
                        </a>
                    </li>
                {% endif %}
                <li class="nav-item">
                    <a class="nav-link text-white" href="{% url 'workshop_app:workshop_type_list' %}">
                        Workshop Types
                    </a>
                </li>
            </ul>
            <div class="my-2 my-lg-0">
                <ul class="navbar-nav mr-auto">
                    <li class="nav-item dropdown">
                        <a class="nav-link dropdown-toggle text-white" href="#" id="navbarDropdown" role="button"
                           data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                           <span class="material-icons va-middle">account_circle</span>
                            <p class="d-inline va-middle">
                                {{user.get_full_name|title}}
                            </p>
                        </a>
                        <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                            <a class="dropdown-item" href="{% url 'workshop_app:view_own_profile' %}">Profile</a>
                            <a class="dropdown-item" href="{% url 'password_change' %}">
                                 Change Password
                            </a>
                            <a class="dropdown-item" href="{% url 'workshop_app:logout' %}">Logout</a>
                        </div>
                    </li>
                </ul>
            </div>
            {% endif %}
        </div>
    </div>
    </nav>
{% endblock %}

<div id="main" class="base-content">
    {% block content %}
        <h1>Base Template Content. Please override me</h1>
    {% endblock %}
</div>

<script src="{% static 'workshop_app/js/jquery-3.4.1.min.js' %}"></script>
    <script src="{% static 'workshop_app/js/popper.min.js' %}"></script>
    <script src="{% static 'workshop_app/js/bootstrap.min.js' %}"></script>
    <script src="{% static 'workshop_app/js/toastr.min.js' %}"></script>

    <script>
      // Toastr accessibility and UX options
      if (typeof toastr !== 'undefined') {
        toastr.options = {
          closeButton: true,
          progressBar: true,
          newestOnTop: true,
          preventDuplicates: true,
          positionClass: 'toast-bottom-center',
          timeOut: 4000,
          extendedTimeOut: 2000
        };
      }
      // Wrap wide tables for mobile horizontal scrolling + enhance forms + navbar UX
      (function() {
        $(function() {
          // Responsive tables
          $('table').each(function() {
            var $t = $(this);
            if (!$t.parent().hasClass('table-responsive') && !$t.parent().hasClass('table-wrap')) {
              $t.wrap('<div class="table-responsive table-wrap"></div>');
            }
          });

          // Auto-apply Bootstrap form-control for better mobile usability
          $('input[type="text"], input[type="password"], input[type="email"], input[type="tel"], input[type="number"], input[type="url"], input[type="search"], select, textarea')
            .each(function() {
              var $el = $(this);
              if (!$el.hasClass('form-control')) { $el.addClass('form-control'); }
            });

          // Ensure submit buttons are styled
          $('input[type="submit"], button[type="submit"]').each(function() {
            var $b = $(this);
            if (!$b.hasClass('btn')) { $b.addClass('btn'); }
            if (!/\bbtn-/.test(this.className)) { $b.addClass('btn-primary'); }
          });

          // Collapse navbar on link click (for mobile)
          $('.navbar-collapse a:not(.dropdown-toggle), .navbar-brand').on('click', function(){
            $('.navbar-collapse').collapse('hide');
          });
        });
      })();
    </script>

<script>
{% if messages %}
  {% for message in messages %}
    (function () {
      var tag = "{{ message.tags|default:'info'|escapejs }}".trim().split(' ')[0];
      if (['success','info','warning','error'].indexOf(tag) === -1) tag = 'info';
      toastr[tag]("{{ message|escapejs }}");
    })();
  {% endfor %}
{% endif %}
</script>

<footer class="footer">
    {% block footer %}
       <div class="container">
           Developed by FOSSEE group, IIT Bombay
       </div> 
    {% endblock %}
  </footer>
</body>
</html>

Python-Screening-Task-1-UI-UX-Enhancement/workshop_booking-master-new/workshop_app/templates/workshop_app/view_profile.html
{% extends 'workshop_app/base.html' %}

{% block title %} Profile {% endblock %}

{% csrf_token %}
{% block content %}

    <div class="container">
        {% if Workshops %}
            <table class="table table-bordered">
                <tr>
                    <th><label for="id_first_name"><h5>First name:</h5></label></th>
                    <th><label for="id_first_name"><h5>{{ coordinator_profile.user.first_name }}</h5></label></th>
                </tr>
                <tr>
                    <th><label for="id_last_name"><h5>Last name:</h5></label></th>
                    <th><label for="id_last_name"><h5>{{ coordinator_profile.user.last_name }}</h5></label></th>
                </tr>
                <tr>
                    <th><label for="id_email"><h5>Email:</h5></label></th>
                    <th><label for="id_email"><h5>{{ coordinator_profile.user.email }}</h5></label></th>
                </tr>
                <tr>
                    <th><label for="id_institute"><h5>Institute:</h5></label></th>
                    <th><label for="id_institute"><h5>{{ coordinator_profile.user.profile.institute }}</h5></label></th>
                </tr>
                <tr>
                    <th><label for="id_phone_number"><h5>Phone Number:</h5></label></th>
                    <th><label for="id_phone_number"><h5>{{ coordinator_profile.user.profile.phone_number }}</h5></label>
                    </th>
                </tr>
                <tr>
                    <th><label for="id_department"><h5>Department:</h5></label></th>
                    <th><label for="id_department"><h5>{{ coordinator_profile.user.profile.department }}</h5></label></th>
                </tr>
                <tr>
                    <th><label for="id_location"><h5>Location:</h5></label></th>
                    <th><label for="id_location"><h5>{{ coordinator_profile.user.profile.location }}</h5></label></th>
                </tr>
                <tr>
                    <th><label for="id_position"><h5>Position:</h5></label></th>
                    <th><label for="id_position"><h5>{{ coordinator_profile.user.profile.position }}</h5></label></th>
                </tr>
            </table>
            <br>

            <div class="container">
            <h2>Workshop Details</h2>
            <table class="table table-bordered">
            <tr>
                <th><label for="id_instructor_name">Instructor name</label></th>
                <th><label for="id_workshop_date">Workshop date</label></th>
                <th><label for="id_workshop_type">Workshop type</label></th>
            </tr>
            {% for workshop in Workshops %}
                {% if workshop.instructor %}
                    <tr>
                        <td><label for="id_instructor_name">{{ workshop.instructor }}
                        </label></td>
                        <td><label for="id_workshop_date">{{ workshop.date }}</label>
                        </td>
                        <td><label for="id_workshop_type">{{ workshop.workshop_type }}</label>
                        </td>
                    </tr>
                {% else %}
                    <tr>
                        <td><span class="badge badge-warning">Pending</span></td>
                        <td><label for="id_workshop_date">{{ workshop.date }}</label>
                        </td>
                        <td><label for="id_workshop_type">{{ workshop.workshop_type }}</label>
                        </td>
                    </tr>
                {% endif %}
            {% endfor %}
            </table>
            </div>
            <br><br>
        {% else %}
            <form action="" method="post">
              {% csrf_token %}
                <div class="row justify-content-center form-group">
                    <div class="col-md-6">
                    <form action="" method="post">
                        <fieldset>
                            {% csrf_token %}
                            {% if form.errors %}
                                {% for field in form %}
                                    {% for error in field.errors %}
                                        <div class="alert alert-dismissible alert-danger">
                                            <button type="button" class="close" data-dismiss="alert">
                                                <i class="fa fa-close"></i>
                                            </button>
                                            <strong>{{field.label}} : {{ error|escape }}</strong>
                                        </div>
                                    {% endfor %}
                                {% endfor %}
                                {% for error in form.non_field_errors %}
                                    <div class="alert alert-dismissible alert-danger">
                                        <button type="button" class="close" data-dismiss="alert">
                                            <i class="fa fa-close"></i>
                                        </button>
                                        <strong>{{field.label}} : {{ error|escape }}</strong>
                                    </div>
                                {% endfor %}
                            {% endif %}
                            <table class="table table-responsive-sm">
                                <tr><td>{{form.title}}</td></tr>
                                <tr><td>{{form.first_name}}</td></tr>
                                <tr><td>{{form.last_name}}</td></tr>
                                <tr><td>{{form.phone_number}}</td></tr>
                                <tr><td>{{form.institute}}</td></tr>
                                <tr><td>{{form.department}}</td></tr>
                                <tr><td>{{form.position}}</td></tr>
                                <tr><td>{{form.location}}</td></tr>
                                <tr><td>{{form.state}}</td></tr>
                            </table>
                            <br>
                        </fieldset>
                        <button class="btn btn-success btn-lg" type="submit">
                            <i class="fa fa-pencil-square-o"></i>&nbsp;Update</button>
                        <a href="{% url 'workshop_app:index' %}" class="btn btn-primary btn-lg">Cancel
                        </a>
                    </form>
                    </div>
                </div>
            </form>
        {% endif %}
    </div>
{% endblock %}